language: node_js

sudo: false

node_js:
  - "0.10"

env:
  global:
  - PROTRACTOR_BROWSERS=firefox
  - KARMA_BROWSERS=Firefox,PhantomJS

install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd sample_project && bower install

script:
  - grunt test
