name: build and run tests
on:
  pull_request
jobs:
  build_and_run_tests_action:
    runs-on: ubuntu-latest
    env:
      PROTRACTOR_BROWSERS: firefox
      KARMA_BROWSERS: PhantomJS,Firefox
      DISPLAY: :99.0
    name: Build and run action on on NodeJs 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version:  10
      - run: sudo apt update
      - run: sudo apt-get install firefox -y
      - name: Install dependencies
        run: npm install
      - run: npm install -g grunt-cli
      - run: npm install -g bower
      - run: npm install --dev coffeescript
      - run: npm rebuild node-sass
      - run: cd sample_project && bower install
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
         run: grunt test

